services:
  maestro:
    container_name: maestro
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - maestro-network
    expose:
      - "5000"
    volumes:
      - ./maestro/:/code

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - maestro-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  maestro-network:
    name: maestro-network
    driver: bridge
