from enum import StrEnum, auto


class Domain(StrEnum):
    BINARY_SENSOR = auto()
    BUTTON = auto()
    CALENDAR = auto()
    CLIMATE = auto()
    COVER = auto()
    DEVICE_TRACKER = auto()
    EVENT = auto()
    FAN = auto()
    HOME_ASSISTANT = auto()
    HUMIDIFIER = auto()
    INPUT_BOOLEAN = auto()
    INPUT_DATETIME = auto()
    INPUT_NUMBER = auto()
    INPUT_SELECT = auto()
    INPUT_TEXT = auto()
    LIGHT = auto()
    LOCK = auto()
    MAESTRO = auto()
    MEDIA_PLAYER = auto()
    NOTIFY = auto()
    NUMBER = auto()
    PERSON = auto()
    RAINBIRD = auto()
    REMOTE = auto()
    SELECT = auto()
    SENSOR = auto()
    SHELL_COMMAND = auto()
    SONOS = auto()
    SUN = auto()
    SWITCH = auto()
    UPDATE = auto()
    WEATHER = auto()
    ZONE = auto()
