# Framework Configuration Errors
class MaestroConfigurationError(Exception): ...


class SchedulerMisconfiguredError(MaestroConfigurationError): ...


class MissingScriptsDirectoryError(MaestroConfigurationError): ...


class NotifActionMappingError(MaestroConfigurationError): ...


# Home Assistant Client Errors
class HomeAssistantClientError(Exception): ...


class EntityDoesNotExistError(HomeAssistantClientError): ...


class MalformedResponseError(HomeAssistantClientError): ...


# Entity & Attribute Errors
class EntityError(Exception): ...


class EntityConfigurationError(EntityError): ...


class StateOverwriteNotAllowedError(EntityError): ...


class AttributeDoesNotExistError(EntityError): ...


class EntityOperationError(EntityError): ...


class EntityMissingFromRegistryError(EntityError): ...


class MalformedRegistryModule(EntityError): ...


# Trigger Errors
class TriggerError(Exception): ...


class EventTriggerOverrideError(TriggerError): ...


# Unit Testing Errors
class UnitTestFrameworkError(Exception): ...


class MockEntityDoesNotExistError(UnitTestFrameworkError, EntityDoesNotExistError): ...
